spring:
  application:
    name: point-ai-code-mother-backend
server:
  port: 8123
  servlet:
    context-path: /api

  # springdoc-openapi????
  springdoc:
    group-configs:
      - group: 'default'
        paths-to-match: '/**'
        packages-to-scan: com.point.pointaicodemother.controller